language: android
android:
  components:
    - build-tools-20.0.0
    - android-L
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "https://github.com/viharsanghavi/DevOps_Assignment.git"
  skip_cleanup: true
  on:
    tags: true