language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
    - compileSdkVersion-23


before_install:
 - chmod +x gradlew

 deploy: 
   provider: releases 
   file: TravisExample.apk 
   skip_cleanup: true 

