language: android
sudo: false
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
    - compileSdkVersion-23

before_install:
  - chmod +x gradlew

after_success:
- sh set_tags.sh


before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

deploy:
  provider: releases
  username:viharsanghavi
  password:home1996
  file: "build/Calculator*release*.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: viharsanghavi/DevOps_Assignment






